import Head from 'next/head'
import Image from 'next/image'
import text from 'next/router'
import styles from '../styles/Layout.module.css'

export default function Home({articles}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>next app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1> Hello next js</h1>
      {articles.map(article=>  <> <h1> {article.title} </h1> 
        <p>  {article.body} </p>
        
       </> )}
    </div>
  )
}

export const getStaticProps= async ()=>{
  const res= await fetch (`https://jsonplaceholder.typicode.com/posts?_limit=5`);
  console.log(res)
  const articles=await res.json();
  return {
    props:{
      articles
    }
  }
}
